#!/usr/bin/env bash

echo "syncing dotfiles"
pushd ~/.dotfiles
git add .
git commit -m 'automated dev commit'
git push
popd

echo " "
echo "syncing dev"
pushd ~/dev
git add .
git commit -m 'automated dev commit'
git push
popd
