#!/usr/bin/env bash

folder="$HOME/Studium/notes"
terminal="kitty"

newnote() {
  name=$(wofi --dmenu --prompt "Enter a name:" <<<"") || exit 0
  [[ -z "$name" ]] && name=$(date +%F_%T | tr ':' '-')
  setsid -f "$terminal" -e nvim "$folder/$name.md" >/dev/null 2>&1
}

selected() {
  choice=$(printf "New\n%s" "$(find "$folder" -maxdepth 1 -type f \( -name '*.md' -o -name '*.typ' \) -printf '%f\n' | sort -r)" | wofi --dmenu --prompt "Choose note or create new:" --insensitive) || exit 0

  case "$choice" in
  New) newnote ;;
  *.md) setsid -f "$terminal" -e nvim "$folder/$choice" >/dev/null 2>&1 ;;
  *.typ) setsid -f "$terminal" -e nvim "$folder/$choice" >/dev/null 2>&1 ;;
  *) exit 0 ;;
  esac
}

selected
