#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed unzip fzf
sudo pacman -S --noconfirm --needed pipewire wireplumber xdg-desktop-portal-hyprland
sudo pacman -S --noconfirm --needed wofi tmux thunar swaync waybar kitty starship
sudo pacman -S --noconfirm --needed zsh zsh-autosuggestions zsh-syntax-highlighting
sudo pacman -S --noconfirm --needed hypridle hyprpaper
sudo pacman -S --noconfirm --needed ttf-font-awesome ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols
sudo pacman -S --noconfirm --needed nwg-look gruvbox-dark-gtk
